# Generated by Django 5.0.7 on 2025-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='last_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpath',
            name='legend_badges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpath',
            name='tests_taken_today',
            field=models.IntegerField(default=0),
        ),
    ]
