# Generated by Django 5.0.7 on 2025-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
